In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
import numpy as np

In [141]:
def pivotesUnitarios(matriz, const):
    matriz = matriz.astype(float)
    const = const.astype(float)
    size = matriz.shape[0]
    
    for i in range(size):
        diag = matriz[i][i]
        for j in range(size):
            if(i==j):
                matriz[i][j] = diag/diag #aqui se cubre el caso de pivotes negativos
            else:
                matriz[i][j] = matriz[i][j]/diag
        const[i] = const[i]/diag
    return matriz, const

In [195]:
def metodoGaussJordan(matriz, const):
    matriz = matriz.astype(float)
    const = const.astype(float)
    size = matriz.shape[0]
    
    for i in range(size):
        matriz, const = pivotesUnitarios(matriz, const)

        for j in range(size):
            if(i==j):
                continue
            else:
                valor = matriz[i][j]
                if(i+1<size):
                    matriz[i+1] = matriz[i+1]*valor
                    const[i+1] = const[i+1]*valor
                
                    matriz[i] = matriz[i]-matriz[i+1] 
                    const[i] = const[i]-const[i+1]
                else:
                    matriz[i-1] = matriz[i-1]*valor
                    const[i-1] = const[i-1]*valor
                    
                    matriz[i] = matriz[i]-matriz[i-1] 
                    const[i] = const[i]-const[i-1]
    matriz, const = pivotesUnitarios(matriz, const)
    return const

In [222]:
metodoGaussJordan(np.array([[5,7],[12,8]]), np.array([9,8]))

array([-0.36363636,  1.54545455])

In [223]:
np.linalg.solve(np.array([[5,7],[12,8]]), np.array([9,8]))

array([-0.36363636,  1.54545455])

metodoGaussJordan(np.array([[5,7,1],[12,8,4],[3,4,7]]), np.array([9,8,7]))

In [199]:
np.linalg.solve(np.array([[5,7,1],[12,8,4],[3,4,7]]), np.array([9,8,7]))

array([-0.5,  1.6,  0.3])

In [218]:
c = np.array([[5,7,1],[12,8,3]])

In [219]:
c.shape

(2, 3)

In [221]:
c.shape[0]

2

In [33]:
t = np.insert(c,c.shape[0]*c.shape[0],d)
np.asmatrix(t)

matrix([[1, 0, 2, 0, 8, 9]])

In [23]:
np.array([[1,0],[2,0]])[0][0]

1

In [16]:
metodoGauss(np.array([[1,0],[2,0]]), np.array([1,7]))

array([[2, 7],
       [3, 7]])

In [200]:
a = np.array([2,5])
b = np.array([3,5])

In [201]:
a + b

array([ 5, 10])

In [202]:
a = [2,5]
b = [3,5]

In [203]:
a+b

[2, 5, 3, 5]

In [228]:
np.random.uniform(low=0, high=2*np.pi)

2.455901387453333